- hosts: jumpbox
  gather_facts: false
  vars:
    instance_list:
      - { name: 'app1', groups: 'apps', floatingip: '', ip: '' }
      - { name: 'app2', groups: 'apps', floatingip: '', ip: '' }
      - { name: 'appdb1', groups: 'appdbs', floatingip: '', ip: '' }
      - { name: 'frontend1', groups: 'frontends', floatingip: '', ip: '' }
    flavor_name: m2.small
    deployment: dev

  tasks:
  - name: Create a server instance
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
#####      name: "{{ webserver_name }}"
      image: rhel-guest
      meta: "group={{ item.groups }},deployment_name={{ deployment }}"
#####      meta: "group={{ webserver_group }},deployment_name={{ deployment }}"
      flavor: "{{ flavor_name }}"
      security_groups: ICMP_and_SSH
      key_name: ansible_ssh
      nics:
      - net-name: int_network
      userdata: |
        #!/bin/bash
        curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
        cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
        curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
        cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
    register: "{{ item.name }}_ip"
#####    register: webserverip
    with_items: "{{ instance_list }}"
    ignore_errors: true

  - name: Add floating IP to webserver
    os_floating_ip:
      cloud: ospcloud
      state: present
      reuse: yes
      server: "{{ item.name }}"
      network: ext_network
      wait: true
      timeout: 180
    register: "{{ item.name }}_fip"
    with_items: "{{ instance_list }}"
    ignore_errors: true

  - name: Show webserver public IP - High View
    debug: var="{{ item.name }}_fip"
    with_items: "{{ instance_list }}"

  - name: Show webserver public IP
    debug: var="{{ item.name }}_fip.floating_ip.floating_ip_address"
#####    debug: var=webserverfloatingip.floating_ip.floating_ip_address
    with_items: "{{ instance_list }}"

  - name: Show webserver private IP
    debug: var={{ item.name }}_ip.openstack.private_v4
#####    debug: var=webserverip.openstack.private_v4
    with_items: "{{ instance_list }}"
